apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: ingress-manager-role
rules:
- apiGroups:
  - ""    # 为空表示是core/v1 
  resources:
  - services
  verbs:
  - list
  - watch
  resources:
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - create
  - update
  - delete