apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: demos.example.com # 名字必须与下面的spec字段匹配，并且格式为 '<名称的复数形式>.<组名>'
spec:
  group: example.com
  names:
    plural: demos # 名称的复数形式，用于： URL： /apis/<组>/<版本>/<名称的复数形式>
    singular: demo  # 名称的单数形式，作为命令行使用时显示的别名
    kind: Demo  # 资源清单中需要使用这一形式，一般是大写开头
    shortNames: # 允许在命令行使用较短的字符串来匹配资源
    - dm
    categories:
    - all
  scope: Namespaced # 可以是Namespaced 或者 cluster
  versions:
  - name: v1  # 列举锁支持的版本
    served: true # 每个版本都可以通过served来独立启用或者禁止
    storage: true # 其中只有一个版本被标记为存储版本
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              name:
                type: string
                pattern: '^test$'
    additionalPrinterColumns:   # 定义kubectl需要打印的字段
    - name: CR-Name
      type: string
      jsonPath: .spec.name